module.exports = {
  ...require("./functions/listKeys"),
  ...require("./functions/getKeyKind"),
  ...require("./functions/getString"),
  ...require("./functions/getLong"),
  ...require("./functions/getDouble"),
  ...require("./functions/getError"),
  ...require("./functions/getText"),
  ...require("./functions/getValue"),
  ...require("./functions/deleteKey"),
  ...require("./functions/setString"),
  ...require("./functions/setLong"),
  ...require("./functions/setDouble"),
  ...require("./functions/setText"),
  ...require("./functions/setValue"),
};
