module.exports = {
  ...require("./getKey"),
  ...require("./getKeyKind"),
  ...require("./getString"),
  ...require("./getLong"),
  ...require("./getDouble"),
  ...require("./getError"),
  ...require("./getText"),
  ...require("./getValue"),
  ...require("./deleteKey"),
  ...require("./setString"),
  ...require("./setLong"),
  ...require("./setDouble"),
  ...require("./setText"),
  ...require("./setValue"),
  ...require("./isInfoFile"),
};
